/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2013 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package com.mamashai.tiwechat;

import java.util.HashMap;
import com.tencent.mm.sdk.openapi.*;
import com.tencent.mm.sdk.modelmsg.*;
import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;

import org.appcelerator.titanium.TiApplication;
import org.appcelerator.kroll.common.Log;

@Kroll.module(name="TiwechatAndroid", id="com.mamashai.tiwechat")
public class TiwechatAndroidModule extends KrollModule
{

	private IWXAPI api;
    private String weichat_key = "wxf0f8850c3a525af7";

	// Standard Debugging variables
	private static final String TAG = "TiwechatAndroidModule";

	// You can define constants with @Kroll.constant, for example:
	// @Kroll.constant public static final String EXTERNAL_NAME = value;
	
	public TiwechatAndroidModule()
	{
		super();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app)
	{
		Log.d(TAG, "inside onAppCreate");
		// put module init code that needs to run when the application is created
	}

	@Kroll.method
	public String shareSession(String title, String desc, String url, String thumb_url)
    {
        Log.d("TiwechatAndroidModule", "shareSession call begin");
        Log.d("TiwechatAndroidModule", weichat_key);
        api = WXAPIFactory.createWXAPI(TiApplication.getInstance().getApplicationContext(), weichat_key, true);
        //api.registerApp("wxc4e544191aa9121a");
        api.registerApp(weichat_key);
        Log.d("TiwechatAndroidModule", "~~~~~~~~~~~~~~~~~~~~~~register api successful~~~~~~~~~~~~~~~~~~~~~~~~");
        WXWebpageObject webpage = new WXWebpageObject();
        webpage.webpageUrl = url;
        WXMediaMessage msg = new WXMediaMessage(webpage);
        msg.title = title;
        msg.description = desc;
        com.tencent.mm.sdk.modelmsg.SendMessageToWX.Req req = new com.tencent.mm.sdk.modelmsg.SendMessageToWX.Req();
        req.transaction = "session";
        req.message = msg;
        req.scene = 0;
        api.sendReq(req);
        Log.d("TiwechatAndroidModule", "~~~~~~~~~~~~~~~~~~~~~~share session end~~~~~~~~~~~~~~~~~~~~~~~~");
        return "ok";
    }

    @Kroll.method
    public String shareTimeline(String title, String desc, String url, String thumb_url)
    {
        Log.d("TiwechatAndroidModule", "shareTimeline call begin");
        Log.d("TiwechatAndroidModule", weichat_key);
        api = WXAPIFactory.createWXAPI(TiApplication.getInstance().getApplicationContext(), weichat_key, true);
        //api.registerApp("wxc4e544191aa9121a");
        api.registerApp(weichat_key);
        Log.d("TiwechatAndroidModule", "~~~~~~~~~~~~~~~~~~~~~~register api successful~~~~~~~~~~~~~~~~~~~~~~~~");
        WXWebpageObject webpage = new WXWebpageObject();
        webpage.webpageUrl = url;
        WXMediaMessage msg = new WXMediaMessage(webpage);
        msg.title = title;
        msg.description = desc;
        com.tencent.mm.sdk.modelmsg.SendMessageToWX.Req req = new com.tencent.mm.sdk.modelmsg.SendMessageToWX.Req();
        req.transaction = "timeline";
        req.message = msg;
        req.scene = 1;
        api.sendReq(req);
        Log.d("TiwechatAndroidModule", "shareTimeline call end");
        return "ok";
    }

    @Kroll.method
    public String loginWeixin(String user_id){
    	api = WXAPIFactory.createWXAPI(TiApplication.getInstance().getApplicationContext(), weichat_key, true);
        api.registerApp(weichat_key);
        final SendAuth.Req req = new SendAuth.Req();
        req.transaction = "login";
		req.scope = "snsapi_userinfo";
		req.state = user_id;
		api.sendReq(req);

		return "ok";
    }
    
    @Kroll.method
    public String isWeixinInstalled(){
    	return "yes";
    }

	// Methods
	@Kroll.method
	public String example()
	{
		Log.d(TAG, "example called");
		return "hello world";
	}
	
	// Properties
	@Kroll.getProperty
	public String getExampleProp()
	{
		return weichat_key;
	}
	
	
	@Kroll.setProperty
	public void setExampleProp(String value) {
		weichat_key = value;
	}

}

